### PR TITLE
Fix BEEF validation issues and refactor validation logic (#211, #96)

### LINKED ISSUE #96: [BUG]There are no leaves at height: ...
## Bug Description

So, for specific transaction:

`0100beef05fe3763190001020000e29fffbb85699957a9ab28299f182218b89873f9e3ca2ed81f2623502fcde7a10102c60ebb010343021cf98872306f484b906acc038b1deecfdf19673386eb7feb6bfe3963190005020000a04cd063b9dcfc44d10749acbc997a341b70d6004e84daa262807da7aff9d8920102045660c3170ef44027f44bdd1d7e2a57a70dd29040873655e122f541979e570e0101009a81b73ef18aed0bab8b151d1715792caf8dd3e7be4b1956e54a436a33692807010100b7050f4dd84980343211994eed88df39f7906a0b7a80c658b15ebb5c8891a1d7010100e694b36062b7586daf25c700cbddd9209c99c537e99c7123043d0d8ee4781745010100bd7e2599fd6d384c25bc4f619b0c75fe5d0c91a4b2356e3b2d5ab566f433fee6fe3c63190004040000968ef88320100a445d7f36793f2e6513a64a5370969b6a5837be156f87b2881e010273fa7fc6d88c8b61c5973abac80653255bfe57c83fb337fa7aeaacd8b5dc526402025b0b1a18502aa4cd896102b35362b6861728b1f14f4ed5c6197e83d17a16927a030223d4af97499600ee164f846a28b20d8a7cf5dbae2ef67012514d560761328abc000101004456c093bdbfe719cc33ce106c11e112190127d8664b10e21c0be1ff4bc5edf1010100efa02a414be05a36f67d7d9db5f0363e34d9e5c3dd480396cb92f5a5c54cec24fe43631900010200007c577df26a7ab429e0cd394aa09b6889a8f4aca6e31df5bc15f28f6103c5b5880102d9f4c0796c1db1fc1efe4d5ccf5aecba5786c1fcac98f14d3c1972357fdb3c0afe6e621900010200008cdbd6fe227cfafa6be4500cae6140c84b2ead61318063e92bdb6974f869cf33010259617a9d17562f7c9765e5dfa6a9a393aa2809ca6166a3d7a31c09efcc5070140e010000000cc60ebb010343021cf98872306f484b906acc038b1deecfdf19673386eb7feb6b000000006a47304402206ab6babb9e60c3a681e09611a2af513c63a94fff5752a7b9b17b3910e6652d1a02207994b669a72449456a0710f6a514ae0097198962a19fa8d9e58eeed66adc81ea4121025a270010d0392c61a0ee274d88287b5d4db563c6afa4574615181e6769ab47d3ffffffff045660c3170ef44027f44bdd1d7e2a57a70dd29040873655e122f541979e570e000000006b483045022100a9da20a540ae2309fccb48d0122c24ec1dab6af750a8e63268b861aced14c0fd02207d0518f38a4a1b9fb9a64e97d1917e1b5005115fa8b79db64e8cb992d43b79964121025a270010d0392c61a0ee274d88287b5d4db563c6afa4574615181e6769ab47d3ffffffff73fa7fc6d88c8b61c5973abac80653255bfe57c83fb337fa7aeaacd8b5dc5264010000006a473044022012e0ba77c100ee3e54e300fd8d8e7ad7db92f669be1a495fa6acde81b0e799ef02204c0886bc6040bb728d7add8c137bd2e3473cfd21d0d041a370a5bc20f67beeb04121025a270010d0392c61a0ee274d88287b5d4db563c6afa4574615181e6769ab47d3ffffffff5b0b1a18502aa4cd896102b35362b6861728b1f14f4ed5c6197e83d17a16927a010000006a47304402204d62b7a3164c6010398ab3f34caf16cac24ac1767a73d2f86690deb60f24d828022052a2e6bb49bfdb690a8d1e104598ce28c188da5caf7c1231dbfbc0c5fbd73d3b4121025a270010d0392c61a0ee274d88287b5d4db563c6afa4574615181e6769ab47d3ffffffff23d4af97499600ee164f846a28b20d8a7cf5dbae2ef67012514d560761328abc010000006a473044022015c70bd3d3f4ed6193a151a9affd2fe698c5fce35d41bd4fa0a062de5d18531a02207b8537ccee79fe1077f94e47298c5e88a93cb7194505c97937f7237bd45fdca14121025a270010d0392c61a0ee274d88287b5d4db563c6afa4574615181e6769ab47d3ffffffffd9f4c0796c1db1fc1efe4d5ccf5aecba5786c1fcac98f14d3c1972357fdb3c0a000000006a4730440220400cd17bc933955cedbdb8c05b9638bd1bc85c188d7384582adb266da484d146022021a86979b12373615b6979ed99715f8cb90df90a0afd978dd940f47d992d6ef24121025a270010d0392c61a0ee274d88287b5d4db563c6afa4574615181e6769ab47d3ffffffff61e19da2629900ba8be5716ef767ba7d60e0f86e96b246b3ff224536ecb606ca000000006b4830450221008dc5f8438885760206114a90daf261769f73f14b2c333b2683cebd931438e8bd02200d8f7ee950c62373dab96121ea4d7e6ea8b7b00ca5eb3d84590ff7425924066d4121025a270010d0392c61a0ee274d88287b5d4db563c6afa4574615181e6769ab47d3ffffffffde750a577972bc7836871dcbef495cb71d77377e5c9ad1c0259245167fac53d0000000006b483045022100da367ba4ac7d3b92fa1c370f095a1833cfa4343c303cf7f08b370656dad66a2802204c222e0c0029bdc0d6ee16751ee25f1b15ed7afe6776bfe8df5a002401bedd1c4121025a270010d0392c61a0ee274d88287b5d4db563c6afa4574615181e6769ab47d3ffffffffeb4a0cd282249bd4e0a3d8c70cb33e045105506caebff8fd6afa93c2834bfa60000000006b483045022100aa1e1a5c1ad4f30043af96892d4aea2b54a2cd861c2d35f3ca1038056019207102201882ca15c7058123aea54ac59ff8ae1f3506031d704f78283d1c3cf716d12f644121025a270010d0392c61a0ee274d88287b5d4db563c6afa4574615181e6769ab47d3ffffffff5c61ae618cdbd4d4368f0482d83318c145ee072dac5c3912db9dfcefd1a9aedf010000006a473044022048c626b5b8302ad617d78e07a121009117e682816010a284752262a7bf7259cb022035bc754bbea7a3146b8009bd618646b2c06c82d35873607cebabbb14a222a6194121025a270010d0392c61a0ee274d88287b5d4db563c6afa4574615181e6769ab47d3ffffffffae2bdb78cd7f2b378c009c92a53b3bd43c1dbc853e908ca688d15ea379f7b019000000006a473044022043504e1317ee042e3dcf47b3f67b4378f30a3a3133d32f26253c6e052df26a9e02205497d0d7a4a431c7c7ab5db96452c03b0dbb4c0cd39e0f32b8374c0988e5dcf34121025a270010d0392c61a0ee274d88287b5d4db563c6afa4574615181e6769ab47d3ffffffffb73c101a69f724f8583da8006d8acf313a35470e61f098bb3c70330b5fd63139000000006a47304402205710cfde3589f5c6e97138fd209631043711e06b2677f65408c26e5d705dc6910220021fcbaf71763e102d7808cfe398edd9ca0b7367ddea03b62f6108d48c8035af4121025a270010d0392c61a0ee274d88287b5d4db563c6afa4574615181e6769ab47d3ffffffff010a000000000000001976a914cd9cb8276894790648a7dd68e917c6029251de6e88ac000000000001000000015de78940b72e2e2d3a0e0a795fde144d48bbf52b1ad0e87f8d42736234ed574b000000006a47304402202e1ee6b75f96ca96e127d8d09d7ad8c4d3c93548ae90d2b814acc95cbc115a280220293619baacefac2667dd19c8119a8b99c88a70004a322c1310f539b94c5e4a75412103dbc21ebd13da57220deff50a0465799151ce682a5dc2bd13dcb6809f413c4108ffffffff0201000000000000001976a91423f2562a8092ed24eddc77c74387b44c561692a188ac01000000000000001976a914c753bcccbfd437301b382587951516250edc2d7788ac000000000100010000000159617a9d17562f7c9765e5dfa6a9a393aa2809ca6166a3d7a31c09efcc507014130000006b4830450221009399820c643e5f2699b07ffa3289b22c6124e1317fd1ec41fb2431047dcf552f02201b7ee3ee3422fe1c33d8869a34a28fadddb9b790b3c5b332b7fafaaa8d4b413c4121029b15053bc379e2378cd6a84fb40b761b4e400faa4efd09280443731d4b3f8a8cffffffff0201000000000000001976a91423f2562a8092ed24eddc77c74387b44c561692a188ac03000000000000001976a9144ed83e2b3aae481f7fa48321024eb3d8e1f7417888ac0000000001010100000001045660c3170ef44027f44bdd1d7e2a57a70dd29040873655e122f541979e570e010000006b483045022100d3f3502c419a585f90c9584212fd9db2eb90eb388ffbc8f3b25adc36af5e6c620220687a84086fc458d9c97e38fa0b5c043ed5411939a15623ad208566178da9d931412102e3bee971d5b655dfd5a7e18eb7947791421db1968bae5a16f81369a4e0fad674ffffffff0201000000000000001976a914f8cfe0e2a34b16c5c463ae9f19ecc8a04913e33588ac01000000000000001976a91423f2562a8092ed24eddc77c74387b44c561692a188ac000000000102010000000159617a9d17562f7c9765e5dfa6a9a393aa2809ca6166a3d7a31c09efcc5070140a0000006b483045022100ec7c726828d672a724d2e35583fa6bad1cf50a85e90fdd8af8da0a532ef83ab502200db3c7c7fe7f557501ad8523620dc76316faa633cb0289d96408d2199eed93b6412102e74cc80c381ed86d4b2f8fe0b6681f21bb97ef1e99f13d31d99832b83b7169f3ffffffff0203000000000000001976a9149bbd5a31e27a6ebcefbde5957b0d34e01726bb2788ac01000000000000001976a91423f2562a8092ed24eddc77c74387b44c561692a188ac00000000010201000000015b0b1a18502aa4cd896102b35362b6861728b1f14f4ed5c6197e83d17a16927a000000006b483045022100dfd895883db0a4bc23b6aca041708dc48830a68e456f3442c3779c3ef858a8e40220354d339d4db225468161674774230104371bde3322c1fe45e8a3b8817a594f2d4121023a2dfb6c2fa94cd96f05cda46b04654663af00c198cd8d47085d2b1c8b95b177ffffffff0201000000000000001976a914af863962136cc2e96409345aebdc12ef0eaef26188ac01000000000000001976a91423f2562a8092ed24eddc77c74387b44c561692a188ac000000000102010000000159617a9d17562f7c9765e5dfa6a9a393aa2809ca6166a3d7a31c09efcc5070141b0000006b483045022100a8988ca7dfc9db558ecfa282089e047d65cd1e48331681bdcdc0a9b02dbf738f02202609052607b61172ed80abc530fbe100eae3ce8ea34fd1216b1189a6076ca9c1412103db623562410ab6999e4dd32c0ce178dff7ea607f41d621ba33506e1d4cf7d9ccffffffff0201000000000000001976a91423f2562a8092ed24eddc77c74387b44c561692a188ac03000000000000001976a914f1ba3a1ab6d9f383657d59ebb2137465f2cb7d8a88ac0000000001030100000001ee353cb1f4cb2b19bf7d2328f3c0a5fa2bd1aa94d0795934dd1d63756583b0ac000000006b4830450221009e779c3f04bb056da180b50ad3972b6fd552c52bd6337f572f08ca656625a4530220648e1fc5872d9bc3846f78edd79b4dc406dfecbab359e46b53c7d478747141684121022280e60c665907fb88a97f5e74dd4e1db0eba60a4dad18158ea8eb9495e242daffffffff2005000000000000001976a914e073bf1bf7b6160f7f68403a374717fdc4cce86d88ac4a000000000000001976a9145bbe83249067ec745d8e270c121c651f56ec2cf188ac42030000000000001976a914983a29113517769da9eace0ec25b760ad09c5f5988ac05000000000000001976a91402c75f3ec99db76e6cd2658a7c83c8bf21a0d14b88ac05000000000000001976a914de454fbce4e1be341d11cd5545664771f72d184088ac25000000000000001976a914b5c2a6831b5cdbc8985517f5d912064449ad118088ac3d010000000000001976a914e4566d91c063f99f7418f12d670b5da320160c8188ac05000000000000001976a914616dc74c3945895eafdac8da9174f95b4d91d75b88ac03010000000000001976a91476ae1c3f2c01a9a5f2aa7696cc9b89ea55b0d01688ac0d000000000000001976a9146d805d21013cc20351e5cd55ecaa7dcee59f2fde88ac05000000000000001976a914613408f68bdde1ff3f77a96abd4956a472766acf88ac21000000000000001976a914d7f0bcfa5b5cad93574a960627db60af8dac277c88ac05000000000000001976a9147e088fe21413442569fa59b6a5bf7e8fe6db71e388ac05000000000000001976a914e5ff336cbffc4ffef544ff4d131de68bf9b0aa1488ac05000000000000001976a9142145b563cd2766ba08d33ca0ecb5a6679268dfb788ac05000000000000001976a914da990487dff4910c8891cebcd00a569011f4f05188ac05000000000000001976a914100daf8fa5add521fb87b46ff51657728626c5fe88ac07000000000000001976a914de900668ddecd73f498c8560b8770231bef9616b88ac05000000000000001976a914dd08ccc14ebdcc534bb2320e7d3dba624a7ecd5388ac05000000000000001976a9141c5b5915e67a840fdcefd0db0ca1a1dfaaf4f3cf88ac06000000000000001976a91441815c6352756937fe6b2b17586dd6b39560321188ac05000000000000001976a91471dca8f8631f145ad5721f8387a764ae0ef2599888ac1d000000000000001976a9147e2621372c66ca3c6e6fca8cdb7eac42405d37fe88ac05000000000000001976a914d745ec07218bde8d179d49e4a6feca7f744f57e388ac05000000000000001976a91499456246822c4270ae73d6c7d8e1af690d1d31dd88ac05000000000000001976a914176dc7f479059d28593021e63bcb66bae6c2cc5388ac05000000000000001976a914a48809ce3c763a0a34c24ab2646fdf10cffdbc6588ac05000000000000001976a914e314da9f12f6bd888da53faa616890a2dce9eeb488ac05000000000000001976a91418f9185bb0ca144d934bd4845b3968d545e7ec8188ac17010000000000001976a9149db831932668077f8eebf597976ec61fc6ab90d588ac09000000000000001976a91479b349601390a6216994d44ca618db71e6e811ef88ac06000000000000001976a91451d25ac626a4b7c281b4200a3dcf34caae43f0df88ac0000000001040100000001d9f4c0796c1db1fc1efe4d5ccf5aecba5786c1fcac98f14d3c1972357fdb3c0a010000006b4830450221009a95e614f69f2d300e541f84d3dd4c3b1247f2a0e33e2d4824c01b27c131e2e402206ca8b98f0d60a7599e40c22f7b12341e1c9deede5a878f5b8058daa5df08068741210204f5ac8fe5f95e8f45ce44c68c6ee1af5756e47ea8981f5a9cbd9c8871b43fbfffffffff0201000000000000001976a91423f2562a8092ed24eddc77c74387b44c561692a188ac01000000000000001976a914e3aab0e65b69d0206eacc9ba6a66a7d6418e48b488ac0000000000010000000159617a9d17562f7c9765e5dfa6a9a393aa2809ca6166a3d7a31c09efcc507014070000006b483045022100907eec2cc7d8fd051ac6aac6c8a1ec3b1452b8d9b8c93c2742401ac298118e2002207f39d2a1ec9322842cba006c8aaf30307c88e87a7935780b68ba0bac4f0df255412103918d5589f8e8af4f9343359a6b349f27511f891e1667952b2267290d9a7834feffffffff0201000000000000001976a91423f2562a8092ed24eddc77c74387b44c561692a188ac03000000000000001976a91467093ae40721810ee5f56ec71991c0b2dab1b9d288ac00000000000100000001de750a577972bc7836871dcbef495cb71d77377e5c9ad1c0259245167fac53d0010000006a47304402206c94c911e2d95b04aeab483ec6ca1d0214f7b86d1970476ac1a168c8b79fbe3002206e230db9b20bb665244b1e7528216d2ad15a90e75a0c4a2d8900f5ca2e6eeac64121034ee62aff712b5da30e92ac3c185ff3eee23ab83ddad49303d8574205e5e17c7dffffffff0201000000000000001976a91423f2562a8092ed24eddc77c74387b44c561692a188ac01000000000000001976a91495be8aaed53cdb2d7a84343e332f2652025b88be88ac0000000000010000000159617a9d17562f7c9765e5dfa6a9a393aa2809ca6166a3d7a31c09efcc5070141c0000006a47304402203c1f25c5e41b4a102297c70b35c85530add87f050f244524a491450f4f16ede3022047cd556152fa78696300019c3406af21d82d23e453372c09d82436cbf636cbe9412103d1d8d4c9ca4c805e37456a003d510cb5b528946f2c63cdfd89d5386edbed8091ffffffff0203000000000000001976a914516ed9658f484da42879d94165e78647fccb8aaf88ac01000000000000001976a91423f2562a8092ed24eddc77c74387b44c561692a188ac000000000001000000015c61ae618cdbd4d4368f0482d83318c145ee072dac5c3912db9dfcefd1a9aedf000000006b483045022100b30b58e738ca4e156d34563435d43ba3cd4f0b24ceccff0d9db1aa70786ffd75022058986fb08f83ada19e06216fb8d77796586f0e67271e1fe4889eecbe7baa33c7412102342ea8090d6bc310305d33ae6271e195a8ae0dde83f6383cc5aecf633c1acc0effffffff0201000000000000001976a91423f2562a8092ed24eddc77c74387b44c561692a188ac01000000000000001976a9141a5ba593f23bc897332033324ead93470f4c3ca088ac0000000000010000000159617a9d17562f7c9765e5dfa6a9a393aa2809ca6166a3d7a31c09efcc507014030000006b483045022100d1f4fe5671062bb423f53773fd4a08d11f3ee717119931058b2642aedd46dcd702207ac294b4892dcc4983aa8140f0486884e55a519bedd53e667bb8d04e107961ee41210304863a85badc27c818cacaca9e5582aa19738e3a60d5bf9a6354286c5858ed2affffffff0201000000000000001976a91423f2562a8092ed24eddc77c74387b44c561692a188ac03000000000000001976a91472b7782cd6e8e9d261eec14074a697b86050010e88ac0000000000` 

We have the following error: `error while decoding BEEF\nThere are no leaves at height: 1 which makes this invalid`

It turns out that third bump (index 2) provided in the hex produces the error.
In the bump the tree height is 4 and on the second ( at height: 1) iteration `nLeaves` is 0 which basically is not possible according to the code and prevents the calculation of the proof.

## Steps to Reproduce

submit the mentioned tx to the [https://arc-test.taal.com/v1/tx](url)
## Expected Behavior

It needs to succeed

## Actual Behavior

returns mentioned error

### LINKED ISSUE #202: [BUG] install cmd on readme does not work, replace with go get
## Bug Description

Using the command to install or add to a package fails.

## Steps to Reproduce

run the install command on the README.md

## Expected Behavior

Add it to my existing go project

## Actual Behavior

```
mrz@MrZs-MBP go-bt % go install github.com/bsv-blockchain/go-sdk
no required module provides package github.com/bsv-blockchain/go-sdk; to add it:
        go get github.com/bsv-blockchain/go-sdk
```

## Environment

- macos

## Proposed Fix
```
go get github.com/bsv-blockchain/go-sdk
```

### LINKED ISSUE #211: [BUG] BEEF IsValid/Verify algorithm is unstable - gives different results for the same input BEEF
## Bug Description

The `IsValid`/`Verify` algorithm for BEEF is unstable - calls multiple times it gives different results for the same input BEEF.
The problem happens when a `BEEF` contains transactions that don't have BUMPS - let's say `[not mined] BEEF`

## Steps to Reproduce - try this unit test

Two testcases are not pass:
- Case 1:  `beef v2 from testvectors one-in-one-out [not mined]` - this is generated by our test-vectors utility
    - This BEEF has following structure: `(not mined tx) -> (mined tx)`
- Case 2 `beef v1 mainnet tx [not mined]`
    - I got this BEEF Hex from mem pool - it has much more complex "and real world"  structure

```golang
// place this test function in `transaction/beef_test.go`
func TestBeefVerify(t *testing.T) {
	const iterations = 1000

	tests := map[string]struct {
		hex string
	}{
		// the following [not mined] beefs contain transactions that don't have BUMPS
		// e.g.: (not mined tx) -> (not mined tx) -> (mined tx)
		"beef v2 from testvectors one-in-one-out [not mined]": {
			hex: "0200beef01fde80301010000f6282a580ebf0cebd3edbb4ac129d2d7f8a1b337ab642f70377f3d9040eca1d102010001000000012e3f4683e173b40a20527fe5719633ba070df649983614886e90e45aecf2ac56000000006b483045022100c7ddc5159fc630d28f4beeeafa73bc8d32f25b01909732d8d44b9cdbbc85888502206a0a6269bc47c633441a7b5aff120fd0760024badd660f24f713889c0ee70ecb4121034d2d6d23fbcb6eefe3e80c47044e36797dcb80d0ac5e96e732ef03c3c550a116ffffffff01a2860100000000001976a91494677c56fa2968644c90a517214338b4139899ce88ac00000000000100000001f6282a580ebf0cebd3edbb4ac129d2d7f8a1b337ab642f70377f3d9040eca1d1000000006a4730440220291e6769c2383c82fd3c06de833589d9401dbb55838bdc02a76d8d7a98d3cac302207ad2de40877eab59981f2d46dba1cdefd40846db840ae24094eb07688b3e4ee64121034d2d6d23fbcb6eefe3e80c47044e36797dcb80d0ac5e96e732ef03c3c550a116ffffffff01a0860100000000001976a9143cf53c49c322d9d811728182939aee2dca087f9888ac00000000",
		},
		"beef v1 from mainnet tx [not mined]": {
			hex: "0100beef02fe22d10d000a04fd4c02021f0ade7298c9ee505c4ce728eff01b8ee5afebfd6bf78fc055de007adc1b9045fd4d020090bc5a08cf51172b344a5ffbe3ff7be0257a7ac1ffe635d2a2e4b3c609580594fd5602024d985cfd5e069fabc0af08d61d29dc7bb73e4ce2d7fe5f67078e224330b7eb04fd570200c73c2513231ea9f077fc213f38b69ce6ddc6a547ee7f5a8fef05433036add1ac02fd27010029634f4fdbad28cbb98b69df1526b0a6fb8003d301eee886ce7b50721af06185fd2a0100524ca2123d76c175e7775c63558f8c9559e75c12be22192ba3f01ad69251d39102920001752ececf0498cd217680ffa35036213ec65192e547a82fd87dda64745bc57c9400ed1c963033420dd37b50a52b0106fce7f3b17797328ad06197ba14b3c02406510248000773709f08fb89f4dd3f6c1ecdc533e57956d684d123f55d0a1c2fa81d497e5c4b00e6fa5029ff33b5039dcf1ad29d48ec31a3f1280e05228a09a45fff89773117c30224008d830b0871e68181c11fa55bcfc7b4ba4cfe7c141c83e5572c241e16b5501c4925002de377765a914b52423169c000e6f01e022a6d82c624eec484d7de37bf98cea8011300032584497fb4c4d774f0e5b9f60cfe71020dfa4d62be03004c43c27b93c4b1e5010800b738e56ae3afbd6b9ea3a5f2ee28105197a5b047ea90c09af8388a743faef7e50105006c9ab3fde287ab528744668c0d472bb20b8408af403cc17155d8d5770b1a758e0103009bfb3e063448a27874885f3914a52f4793c38cfc754856008b47a5ba944de7d0010000b2ed8e6765ee98e38dd452855c7e36b2be0a077e476d717cd7166b15acc87f5efecab20d000a02fd2b02022412eba9148402370dcd9bdebc2335684fa843452f9c903a1926056c2ded9e9dfd2a0200912b4cfa67a29ad0566906d45438f7595e891675a05f196510a70bd7a78978b501fd1401002444c9b082f3b799b43deb4759df3222edb0d318ee658059183bb0ebf7f94a76018b004bcccd23218a409e11f721b2fed87c2da39291b56187e19ab8c588433a4f7364014400c183687dac2384ab0c1578fb458b9c00329614c8bd75a330045375cab2b014a10123009ea881f36d2698031183fc7ddba5577060fac586d9938166b7a2a7886e2521fa011000e35f0f6da83643cdd837d6f4aed1975a1dd0f8f79a4879c56c189645f7dd003a010900ae7f1a9ef7f64782d6a0f09beefc74f03627730992491f2529cc3e03adea221b01050054a684e36d6da791b60ef667425b94656e61c97db48fe6319686e59fb17e3ff40103008e5cfeadb07f2471590fea982cf7b8c6e113cc4cda99e330e517be3bde55db8d010000a022a5a0fbd1be17f9690056818d7308002b62d2b60d1ecd99014ddda5af6bdf050100000002a3513ec0e99df0307459aeabb3ec2447f680543375be279f981d9ab74ff0564e000000006b48304502210093d7862f1b8adefa47cd53c383721beebcd0691c889069d70435a7eef3f5f8e002205d5cd9323670b2e97b5d6b9d7506c7e8e518b35401c432cc00727ba0ece27eca4121020a177d6a5e6f3a8689acd2e313bd1cf0dcf5a243d1cc67b7218602aee9e04b2fffffffff6cf9e14113fe68992d84a2beba57307dc6db17cd5f6c6776ac3d28abdb60054f010000006a47304402205c58c456d527074320ad7d1ee383e3fc2f8423c39e5125161bb9e7ee8b330b7d02206e161f172b8d6ddfde08a9f0607cc224adc1919d510d52daf42868ccc3e808b04121020a177d6a5e6f3a8689acd2e313bd1cf0dcf5a243d1cc67b7218602aee9e04b2fffffffff020c000000000000001976a9147072e2ef390050bc43726d487c117f96da9c534b88ac7a6f0100000000001976a9147072e2ef390050bc43726d487c117f96da9c534b88ac0000000001000100000002ecdbe1d3168f8ac58c0c9a723700de27671132dd532bda051b2b67f53815fa4d000000006b483045022100d9a8278ed88a26b73b2e7a32267572c2c3a5f1692fa3aa2874b4b420f3c6aadf02205ec100c4870a0c8920898554b3f17727b7a60c68ec5bfdc3b17f29a2e449b6854121020a177d6a5e6f3a8689acd2e313bd1cf0dcf5a243d1cc67b7218602aee9e04b2fffffffffa3513ec0e99df0307459aeabb3ec2447f680543375be279f981d9ab74ff0564e010000006b483045022100c4833dc2da31901e50394d493d6f4c2863eb81c2e671c3e17cfa815fc3255199022043029192ed27a3527d8bb60c9c927ac88c8bfa9f8d2f1cd8d789e554ec8e36bf4121020a177d6a5e6f3a8689acd2e313bd1cf0dcf5a243d1cc67b7218602aee9e04b2fffffffff020d000000000000001976a9147072e2ef390050bc43726d487c117f96da9c534b88ac27690100000000001976a9147072e2ef390050bc43726d487c117f96da9c534b88ac00000000010001000000021f0ade7298c9ee505c4ce728eff01b8ee5afebfd6bf78fc055de007adc1b9045000000006b483045022100a44a9236494e95be20a9e7bc96e14bb7bef03e2ce33f338f0081ca99484d929a0220787494efdf7ebd7790599f06ffbb21fb906c6b47c89f180ec8ca62f145e71f484121020a177d6a5e6f3a8689acd2e313bd1cf0dcf5a243d1cc67b7218602aee9e04b2fffffffff4d985cfd5e069fabc0af08d61d29dc7bb73e4ce2d7fe5f67078e224330b7eb04010000006a47304402203efba1a8cf538998a0975949898e42d2c69df36561969c5a29b38cf33511e9580220614f98ddaa9d5bb05fad38010764332964ec1b41f967861679e390236a4efe814121020a177d6a5e6f3a8689acd2e313bd1cf0dcf5a243d1cc67b7218602aee9e04b2fffffffff020d000000000000001976a9147072e2ef390050bc43726d487c117f96da9c534b88ac706f0100000000001976a9147072e2ef390050bc43726d487c117f96da9c534b88ac00000000000100000007720e0554f291086056263b0e0b43d482bd28cb62a63d61d9729d15795cccebd600000000b24730440220197cd052433a71be1b6c31d9ae7807b65e7e90118b789ec30226f0c703e4327d02201ca938d1c3c3831552ed2b0df55deb1eac0bbeb0ef856c2cd5d52a7058ec69854147304402206abca1efc5513bc7e7bea68f033378db2d7399fc2bee0caac97104ba2cad4f950220339053f1aca658ceb45ca43abb941041013af13fc89051aae47a4e59c61bd20dc12102bd45e58523dfc46c2ef3ee325802d324e30a193cd83271e4e2142989626ccefaffffffff8a35b1e15447fcaa5cce7c85431705f009c726b9e7ca90c0a054b8c884cb1b3c00000000b2473044022036590d5105abfcf19e7f19f78e40a844bf3cb8c68588450a4af80ab18502663602202a8e2193a44a37ff66853b8fa499e55098f3c08e36d0cd68e3ab4224c5d778f14147304402204edc61ce6ebbe3426f36fb02e3c6ca9f34ab355a26751d5180b10140b49d925b02206b438187b6d1a539699c66259f74815c2535b646e659960d28fc1f498b10a022c12102bd45e58523dfc46c2ef3ee325802d324e30a193cd83271e4e2142989626ccefaffffffff319787bdc7b90a3a607f86f44c452944e778abbe8ee6761a82b3ae4024e6795702000000b4483045022100e3598caa01b47ea6ca5e8b186f3fc647eeda32ea97ff77719be76cda9504143a02200c996409d852460dd6c371f53603327e8a4ccb39bcf9c34da41ac02116d4e84c41483045022100e7c6e466b5eb1f79eae6d896de2b0ddbda189387e35ccbc9969f43cee416e6730220071dc62f847857973dea94eaaa4226ba39b07e09422cb9f2ce81e3d21572f0f7c12102bd45e58523dfc46c2ef3ee325802d324e30a193cd83271e4e2142989626ccefaffffffff3def520b9880fc97a032e84ce3381da111588e97d6f536a72a6b9aeb3375297302000000b2473044022017700a6811f0db93143a8d9cd92ec320affa762a29d75270a6fcffd1b29183de0220595092b981da29b66e823899010dfe07a4eb53e8eb4ec1b8ee4139ece56b7e6441473044022015b6355e7640d54fb72d3ad93a0d76691fe96cbd589ff6a9196e327d9c41aa4702204ef00e1ad3d133e73ee53d2dc2208f931eabcee519c30419ffdd603f8a56d289c12102bd45e58523dfc46c2ef3ee325802d324e30a193cd83271e4e2142989626ccefaffffffff4df52d1c36b5794a82cd01046fad0ba9e34456b50267bb0e4372c753e8cf08ea00000000b3473044022055cc1b09e7dcdb76344cf2120c60792578f3518e62ecef5fe9ea8fb117338781022058d0ec4741cb9a5380b0478df068333ed45e4f3cb25bc16d9162b683020eb04041483045022100bf49323c19f8d2283a31f8047b07cac04237096d15df014f85661460dbf4c01802205863c8f6935b202e2647a1e6ec45f367cd298bd61ce4c7c3c1c6be738eb6b038c12102bd45e58523dfc46c2ef3ee325802d324e30a193cd83271e4e2142989626ccefaffffffff801c15e3596aeb2859953b4b412a2737944d7d3177ed3d34e2546dac4d50201302000000b2473044022006210e58b3e206f14f2a4dd9536d837b00271b695210f1a1e8a2047d71b4b85402202a6ad9f4ee00dcc99c421e257e46500a19110e319601566403241798e507954b4147304402204e5e10917378c0b4225ba7f5a317bc670359d40afdb1e7e8dd8247928770524202207b77f8e3eb534cba7413c465f9e7d83922478b44e8bf9e62ea726ac807b08647c12102bd45e58523dfc46c2ef3ee325802d324e30a193cd83271e4e2142989626ccefaffffffff912b4cfa67a29ad0566906d45438f7595e891675a05f196510a70bd7a78978b5000000006b483045022100f950eef70d59afd91e988dbb2fa9e620c508a2a71ecc4044ea73981e27dc055302200b30bb9705be23f8bc2fba08c201caf77609abc0e9bb4e42e0826e1809de05504121020a177d6a5e6f3a8689acd2e313bd1cf0dcf5a243d1cc67b7218602aee9e04b2fffffffff030100000000000000d20063036f726451126170706c69636174696f6e2f6273762d3230004c787b2270223a226273762d3230222c226f70223a227472616e73666572222c226964223a22616535396633623839386563363161636264623663633761323435666162656465643063303934626630343666333532303661336165633630656638383132375f30222c22616d74223a2232383730383133227d6876a914b5ff6c546a60342e88e5ebe7dad51a24143383f588ad21020a177d6a5e6f3a8689acd2e313bd1cf0dcf5a243d1cc67b7218602aee9e04b2fac0100000000000000cf0063036f726451126170706c69636174696f6e2f6273762d3230004c757b2270223a226273762d3230222c226f70223a227472616e73666572222c226964223a22616535396633623839386563363161636264623663633761323435666162656465643063303934626630343666333532303661336165633630656638383132375f30222c22616d74223a2231303030227d6876a9145d34be178f0bc32c3d85671427f1e70694ca8a3b88ad21020a177d6a5e6f3a8689acd2e313bd1cf0dcf5a243d1cc67b7218602aee9e04b2fac0100000000000000d30063036f726451126170706c69636174696f6e2f6273762d3230004c797b2270223a226273762d3230222c226f70223a227472616e73666572222c226964223a22616535396633623839386563363161636264623663633761323435666162656465643063303934626630343666333532303661336165633630656638383132375f30222c22616d74223a223137373431363233227d6876a914a5854b1a82f5c71b664a19b64c358f54d6acb18c88ad21020a177d6a5e6f3a8689acd2e313bd1cf0dcf5a243d1cc67b7218602aee9e04b2fac00000000010101000000022412eba9148402370dcd9bdebc2335684fa843452f9c903a1926056c2ded9e9d00000000b3473044022017c67b7d2ec56df57643b97855cbde504772b45b5aa3d3f2f70543d0c7f640e10220102b8fce1bc9e0fa7b633119baae429522ffc08de063770c78a007cb7ab1d2d241483045022100a85692c4ba3828b0f12b6d5c36ff5fffb3e6a0f8a0684ebc59d925c75a64d91c0220776ad270f133ce0f5fc28b8d7ac8dcc6236304346d909ccbb8db3dddb910571bc121036823f82f6c9c279b17c6e5edb0de192a9757778ef978112a62c9a1d17efa4ebaffffffffb05957c4cf6e745f2e147610575f4ba632a84032c86862dec0c656db0ba37911000000006a47304402203bb4c3d0fcae2c72fa6d88f4045447fd8fa2e33afb5867d4092923fa872af67802204faece6a38513d97440c31169a6fc6d69fb4766b4ad9e905218996179c7441f44121020a177d6a5e6f3a8689acd2e313bd1cf0dcf5a243d1cc67b7218602aee9e04b2fffffffff030100000000000000d20063036f726451126170706c69636174696f6e2f6273762d3230004c787b2270223a226273762d3230222c226f70223a227472616e73666572222c226964223a22616535396633623839386563363161636264623663633761323435666162656465643063303934626630343666333532303661336165633630656638383132375f30222c22616d74223a2231303030303030227d6876a914a5854b1a82f5c71b664a19b64c358f54d6acb18c88ad21020a177d6a5e6f3a8689acd2e313bd1cf0dcf5a243d1cc67b7218602aee9e04b2fac0100000000000000ce0063036f726451126170706c69636174696f6e2f6273762d3230004c747b2270223a226273762d3230222c226f70223a227472616e73666572222c226964223a22616535396633623839386563363161636264623663633761323435666162656465643063303934626630343666333532303661336165633630656638383132375f30222c22616d74223a22313030227d6876a9145d34be178f0bc32c3d85671427f1e70694ca8a3b88ad21020a177d6a5e6f3a8689acd2e313bd1cf0dcf5a243d1cc67b7218602aee9e04b2fac0100000000000000d20063036f726451126170706c69636174696f6e2f6273762d3230004c787b2270223a226273762d3230222c226f70223a227472616e73666572222c226964223a22616535396633623839386563363161636264623663633761323435666162656465643063303934626630343666333532303661336165633630656638383132375f30222c22616d74223a2231383730373133227d6876a914b5ff6c546a60342e88e5ebe7dad51a24143383f588ad21020a177d6a5e6f3a8689acd2e313bd1cf0dcf5a243d1cc67b7218602aee9e04b2fac0000000000",
		},

		// the following [mined] beefs contain transactions that all have BUMPS
		"beef v1 from actual testnet tx [mined]": {
			hex: "0100beef01fe849e19000c02fdcf0a02c8c06c5fac63510b2b02ccab974a6ef0b0a4910dd8e881c06964f2b52d7ff415fdce0a00ac05565e579d8c4257313d90ce7bea754aa41add817a0616a9199c84a89d273301fd66050072958bee9c51d1a7511759ef6c73aa03a0533749e887c06514504c466a185fc201fdb202004d106b759b760b423b05be8e53b7ccd44db1cf8c39fd609ee70c316b0a2964df01fd5801003521b209685ae64f5a7f41fcfc5d487fe1b0162ee5a311620c252f6f48714ad101ad000af15dea439d12d3330dc65b5fac8a8e786d80c9f4e8c10dec91807c2fa085380157000e5a9d088abcc6bfb57f6aeb7f12a4fbe63fa07477bef78fa87f967466c374d4012a0083c8207772fb8586071053e855af973a2cce232d45d6a90e3ad403015a003ad1011400074cd69e726d1f7b9f7f1f301f701eef3dd36cbec654ddf7ee897d2567fbc2d4010b00620e7f9bd848d9123aad73e7b28b05e830eaf7d7188f3322d79b2256934026f9010400bbb0cac6a484ac94f774b0c795fa9f116f8251e7cdfe7b374938b8806563f383010300a7074e5aa1e7ffc5754fb762c7853adc20a80c25fad6ad60ddbf80b6d8ad02e40100009c956d581a811c8d45a81b716fbb9c4349c4be011f24c44d236a493b24ca5f4201010000000122ffae11e662c209b8cc5ecce312af425b06f44668d667bb8b09fc04f1e25653010000006b483045022100bac3cea0816c2c8863b6a5207bef9c2236716c58140448d980241f851705872f02201a912284e254e76f33fab9b82eb577921950e9091edf4e79d9a6d00453a23a4e41210231c72ef229534d40d08af5b9a586b619d0b2ee2ace2874339c9cbcc4a79281c0ffffffff0201000000000000001976a914d430654b50459aa04e308c07daf4871185efdc3088ac0d000000000000001976a914cd5ea7065a42329a574b1eb7af9fbbca8a94e44b88ac000000000100",
		},
		"beef v1 from actual mainnet tx [mined]": {
			hex: "0100beef01feb2d20d000402070275108dbcbc9b210d852d90e79f17feebb5ac99640b23055a33daf6aa1860fa670600aaccf30ae2fc73c7ed85601ce3aff36361b8a197e1a4860da4288b452d903a4a010200d1e94851f84a3aa5c2d893c386607471b67f2eec27f8f116c1e05197e84d0c6b010000d87dca62e921e12ed2bc69fc988a922065fa38ae6ad62b07417bfd3e9f74697101010051bb5ce45a8c5e4101246e1f48ae969ef6fc337000fd9dfa4db39e2e114c85af010100000001dc3a61bb7feca472a600ac66b1cbea3e119500853b6aa4f6839cae84e0c3c862010000006b48304502210085bd20643d927b9c505b2bd27c84f447c7407bcdca8d727510d9181a39d71a6f02204210132e103a4460c4fea60d5a915b73861d00876a8f1fa50936100ae8f72ad4412102ae912ff4cf65d91f8174fc8620ea4c627fb9ae282a915ff2fa3dd31044971177ffffffff0200000000000000004c006a4953454e534f52415f50524f4f4601012a0104f81c1b83c30000000000000001000000006878cec70001727e4a61a0971fdebe760d73e8a9de80e507062482806701eced6c7ee3df20bd87020000000000001976a9146c6ec50d57d4ac54ff23ff6482fb6695070c2d7a88ac000000000100",
		},
		"beef v2 from the above BeefSet [mined]": {
			hex: BEEFSet,
		},
		"beef v1 from the above BRC62Hex [mined]": {
			hex: BRC62Hex,
		},
	}
	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			var beef *Beef
			var err error
			failed := 0

			for range iterations {
				// given:
				beef, err = NewBeefFromHex(test.hex)
				require.NoError(t, err)

				// when:
				ok := beef.IsValid(true)

				// then:
				if !ok {
					failed++
				}
			}

			fmt.Print(beef.ToLogString())

			succeeded := iterations - failed
			if succeeded != 0 && failed != 0 {
				t.Log("UNSTABLE IsValid algorithm - it gives different results for the same input beef")
				t.Logf("succeeded %d, failed %d", succeeded, failed)
				t.FailNow()
			}
		})
	}
}
```

## Expected Behavior

All above test cases should pass - the `IsValid` algorithm should return always the same value (for the same beef), regardless how many times we call it

## Actual Behavior

As mentioned above: Case 1 & 2 fail.

Example output from the failed tests:
```
beef v2 from testvectors one-in-one-out [not mined]:
UNSTABLE IsValid algorithm - it gives different results for the same input beef
succeeded 887, failed 113

beef v1 from mainnet tx [not mined]
UNSTABLE IsValid algorithm - it gives different results for the same input beef
succeeded 649, failed 351
```

### PR DESCRIPTION
**Pull request by shruggr**
### Description
This PR fixes multiple BEEF-related issues:
1. Non-deterministic BEEF validation (#211)
2. BEEF parsing panic with "no leaves at height" error (#96)
3. Incorrect validation logic for transactions in BUMPs
4. Confusing method name `SortTxs`

### Root Cause Analysis

**Issue #211**: The validation logic was not properly handling transaction validation order, causing non-deterministic results.

**Issue #96**: The SDK was being too strict during BEEF parsing, panicking when transactions didn't have merkle paths or source transactions. This is valid BEEF data that should be handled gracefully.

**Validation Logic**: The validation wasn't properly checking if transactions appear in BUMPs (have proof) for all DataFormat types.

### Solutions

1. **Fixed validation order** by ensuring transactions with merkle paths are added to the valid set before validating dependent transactions

2. **Removed panic during parsing** - transactions without merkle paths or source transactions are now handled gracefully

3. **Refactored validation logic**:
   - Renamed `SortTxs()` to `ValidateTransactions()` for clarity
   - Added proper validation for `TxIDOnly` and `RawTx` formats by checking if they appear in BUMPs
   - Added verification that `RawTxAndBumpIndex` has accurate bump index
   - Returns a structured `ValidationResult` with categorized transaction lists

4. **Fixed test assumptions** that incorrectly expected all input transactions to be present in BEEF

5. **Performance optimization**:
   - Refactored BEEF implementation to use `chainhash.Hash` directly as map keys instead of string conversions
   - Added `*ByHash` method variants to avoid unnecessary hash/string conversions
   - Updated `collectAncestors` to return `[]chainhash.Hash` instead of `[]string`

### Additional Fixes
- Fixed README installation instructions to use `go get` instead of `go install` (#202)

### Testing
- Added test cases from issues #211 and #96
- Fixed existing tests to work with new validation logic
- All tests pass consistently with proper validation behavior
- No existing functionality was broken

### Changes
- Modified `verifyValid()` to use new `ValidateTransactions()` method
- Added `ValidateTransactions()` method with comprehensive validation logic
- Removed panic in `readAllTransactions()` for missing source transactions
- Updated all test references from `SortTxs` to `ValidateTransactions`
- Fixed test in `TestBeefGetValidTxids` to handle transactions with merkle paths correctly
- Refactored internal BEEF structures to use `chainhash.Hash` for better performance

Fixes #211
Fixes #96
Fixes #202

### CODE REVIEW

**Comment by kuba-4chain** [comment]
Hey, I just added a similar fix here:
https://github.com/bsv-blockchain/go-sdk/pull/213 

I did not see you've already pushed the fix, you beat me to it 😄 I'll close my PR as a duplicate.

There's just one thing, I think that the `b.SortTxs()` function at the beginning of the `verifyValid` method is unnecessary, as it doesn't sort in-place, if I understand this correctly.

Otherwise, thanks for the fix!

File: transaction/beef.go [hunk 1]
```diff
@@ -803,115 +800,214 @@ func (b *Beef) Verify(ctx context.Context, chainTracker chaintracker.ChainTracke
...
+			// RawTx is valid if it appears in a BUMP
+			if txidsInBumps[txid] {
+				validTxids[txid] = true
+				hasProof = append(hasProof, beefTx)
+			} else if beefTx.Transaction != nil {
+				// Check if all inputs are available
+				hasMissing := false
+				for _, input := range beefTx.Transaction.Inputs {
+					if _, exists := b.Transactions[input.SourceTXID.String()]; !exists {
+						missingInputs[input.SourceTXID.String()] = true
```
Comment (chris-4chain) [inline transaction/beef.go]: Since calculating string txid is not zero-time, I suggest to precalculate it when it's used twice. 
```suggestion
				for _, input := range beefTx.Transaction.Inputs {
					sourceTxID := input.SourceTXID.String()
					if _, exists := b.Transactions[sourceTxID]; !exists {
						missingInputs[sourceTxID] = true
```

File: transaction/beef.go [hunk 2]
```diff
@@ -803,115 +800,214 @@ func (b *Beef) Verify(ctx context.Context, chainTracker chaintracker.ChainTracke
...
-		for _, beefTx := range queue {
+	// Iteratively validate transactions that depend on other transactions
+	for len(needsValidation) > 0 {
+		progress := false
+		var stillNeedsValidation []*BeefTx
+
+		for _, beefTx := range needsValidation {
+			// Check if all inputs are valid
+			allInputsValid := true
 			if beefTx.Transaction != nil {
```
Comment (chris-4chain) [inline transaction/beef.go:946]: - Possible Infinite Loop if `needsValidation` contains all nil Transactions
- A corner case is when there is only one "needsValidation" beefTx with nil transaction

File: transaction/beef.go [hunk 3]
```diff
@@ -803,115 +800,214 @@ func (b *Beef) Verify(ctx context.Context, chainTracker chaintracker.ChainTracke
...
+			txid := beefTx.Transaction.TxID().String()
+			result.WithMissingInputs = append(result.WithMissingInputs, txid)
 		}
-		queue = newQueue
 	}
 
-	// Now, whatever is left in queue is not valid
-	for _, beefTx := range queue {
+	// Add txid-only transactions
+	for _, beefTx := range txidOnly {
```
Comment (chris-4chain) [inline transaction/beef.go:986]: Since the length of txidonly is known, I would preallocate memory for `result.TxidOnly` slice.
```suggestion
	result.TxidOnly = make([]string, 0, len(txidOnly))
	for _, beefTx := range txidOnly {
```

File: transaction/beef.go [hunk 4]
```diff
@@ -803,115 +800,214 @@ func (b *Beef) Verify(ctx context.Context, chainTracker chaintracker.ChainTracke
...
-			res.NotValid = append(res.NotValid, beefTx.Transaction.TxID().String())
+			txid := beefTx.Transaction.TxID().String()
+			result.Valid = append(result.Valid, txid)
 		}
 	}
 
-	for k := range missing {
-		res.MissingInputs = append(res.MissingInputs, k)
+	// Populate missing inputs list
+	for txid := range missingInputs {
```
Comment (chris-4chain) [inline transaction/beef.go:1009]: Similar comment ☝️ - preallocate
```suggestion
	result.MissingInputs = make([]string, 0, len(missingInputs))
	for txid := range missingInputs {
```

File: transaction/beef.go [hunk 5]
```diff
@@ -803,115 +828,209 @@ func (b *Beef) Verify(ctx context.Context, chainTracker chaintracker.ChainTracke
...
+
+	return result
 }
 
 func (b *Beef) verifyValid(allowTxidOnly bool) verifyResult {
 	r := verifyResult{valid: false, roots: map[uint32]string{}}
-	b.SortTxs() // Assume this sorts transactions in dependency order
 
+	// Validate and sort transactions
+	vr := b.ValidateTransactions()
```
Comment (chris-4chain) [inline transaction/beef.go:1020]: While the detailed result from `ValidateTransactions` is useful for debugging, it's unnecessary for simple validity verification (which only requires a true/false outcome).

`ValidateTransactions` could return early if any of the following conditions occur, avoiding the need to populate slices that won't be checked.

I think, functions `IsValid` and `Verify` are important enough (SPV) to have specialized/optimized algorithms.
